SET SERVEROUTPUT ON;

/*****************/
/* CRUD - ÁREA   */
/*****************/

CREATE OR REPLACE PROCEDURE CADASTRAR_AREA(NOME IN VARCHAR2) IS
    v_num_areas NUMBER;
BEGIN
    SELECT NVL(MAX(ID_AREA), 0) INTO v_num_areas FROM AREA;
    INSERT INTO AREA(ID_AREA, NOME_AREA) VALUES(v_num_areas + 1, NOME);
END;
/

CREATE OR REPLACE PROCEDURE REMOVER_AREA_CODIGO(CODIGO IN NUMBER) IS
BEGIN
    DELETE FROM AREA WHERE ID_AREA = CODIGO;
END;
/

CREATE OR REPLACE PROCEDURE REMOVER_AREA_NOME(NOME IN VARCHAR2) IS
BEGIN
    DELETE FROM AREA WHERE NOME_AREA = NOME;
END;
/

CREATE OR REPLACE FUNCTION BUSCAR_AREA_CODIGO(CODIGO IN NUMBER) RETURN VARCHAR2 IS
    v_codigo_area VARCHAR2(255);
    v_nome_area VARCHAR2(255);
BEGIN
    SELECT ID_AREA, NOME_AREA
    INTO v_codigo_area, v_nome_area
    FROM AREA
    WHERE ID_AREA = CODIGO;
    
    RETURN 'Codigo(' || v_codigo_area || ') - Área: ' || v_nome_area;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Área com o código ' || CODIGO || ' não encontrada.';
END;
/

DECLARE
BEGIN
    FOR reg IN (SELECT ID_AREA FROM AREA ORDER BY ID_AREA) LOOP
        DBMS_OUTPUT.PUT_LINE(BUSCAR_AREA_CODIGO(reg.ID_AREA));
    END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE ATUALIZAR_NOME_AREA(CODIGO IN NUMBER, NOVO_NOME IN VARCHAR2) IS
BEGIN
    UPDATE AREA SET NOME_AREA = NOVO_NOME WHERE ID_AREA = CODIGO;
END;
/


/******************/
/* CRUD - CLIENTE */
/******************/

CREATE OR REPLACE PROCEDURE CADASTRAR_CLIENTE(NOME IN VARCHAR2) IS 
    v_id NUMBER;
BEGIN
    SELECT NVL(MAX(ID_CLIENTE), 0) INTO v_id FROM CLIENTE;
    INSERT INTO CLIENTE(ID_CLIENTE, NOME_CLIENTE) VALUES(v_id + 1, NOME);
END;
/

CREATE OR REPLACE PROCEDURE REMOVER_CLIENTE_CODIGO(CODIGO IN NUMBER) IS
BEGIN
    DELETE FROM CLIENTE WHERE ID_CLIENTE = CODIGO;
END;
/

CREATE OR REPLACE FUNCTION BUSCAR_CLIENTE_CODIGO(CODIGO IN NUMBER) RETURN VARCHAR2 IS
    v_nome VARCHAR2(255);
BEGIN
    SELECT NOME_CLIENTE INTO v_nome FROM CLIENTE WHERE ID_CLIENTE = CODIGO;
    RETURN 'Codigo(' || CODIGO || ') - Cliente: ' || v_nome;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Cliente com o código ' || CODIGO || ' não encontrado.';
END;
/

CREATE OR REPLACE PROCEDURE ATUALIZAR_CLIENTE(CODIGO IN NUMBER, NOVO_NOME IN VARCHAR2) IS
BEGIN
    UPDATE CLIENTE SET NOME_CLIENTE = NOVO_NOME WHERE ID_CLIENTE = CODIGO;
END;
/


/******************/
/* CRUD - COMANDA */
/******************/

CREATE OR REPLACE PROCEDURE CADASTRAR_COMANDA(ID_MESA_IN IN NUMBER, NOME_CLIENTE_IN IN VARCHAR2, PRECO_TOTAL_IN IN NUMBER) IS
    v_id NUMBER;
BEGIN
    SELECT NVL(MAX(ID_COMANDA), 0) INTO v_id FROM COMANDA;
    INSERT INTO COMANDA(ID_COMANDA, ID_MESA, NOME_CLIENTE, PRECO_TOTAL)
    VALUES(v_id + 1, ID_MESA_IN, NOME_CLIENTE_IN, PRECO_TOTAL_IN);
END;
/

CREATE OR REPLACE PROCEDURE REMOVER_COMANDA(CODIGO IN NUMBER) IS
BEGIN
    DELETE FROM COMANDA WHERE ID_COMANDA = CODIGO;
END;
/

CREATE OR REPLACE FUNCTION BUSCAR_COMANDA(CODIGO IN NUMBER) RETURN VARCHAR2 IS
    v_cliente VARCHAR2(255);
BEGIN
    SELECT NOME_CLIENTE INTO v_cliente FROM COMANDA WHERE ID_COMANDA = CODIGO;
    RETURN 'Comanda ' || CODIGO || ' - Cliente: ' || v_cliente;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Comanda ' || CODIGO || ' não encontrada.';
END;
/

CREATE OR REPLACE PROCEDURE ATUALIZAR_COMANDA(CODIGO IN NUMBER, NOVO_TOTAL IN NUMBER) IS
BEGIN
    UPDATE COMANDA SET PRECO_TOTAL = NOVO_TOTAL WHERE ID_COMANDA = CODIGO;
END;
/


/**********************/
/* CRUD - FUNCIONARIO */
/**********************/

CREATE OR REPLACE PROCEDURE CADASTRAR_FUNCIONARIO(
    ID_USUARIO_IN IN NUMBER, 
    NOME_IN IN VARCHAR2, 
    DATA_ADMISSAO_IN IN DATE, 
    SALARIO_IN IN NUMBER, 
    DATA_NASCIMENTO_IN IN DATE, 
    CARGO_IN IN VARCHAR2
) IS
    v_id NUMBER;
BEGIN
    SELECT NVL(MAX(ID_FUNCIONARIO), 0) INTO v_id FROM FUNCIONARIO;
    
    INSERT INTO FUNCIONARIO(ID_FUNCIONARIO, ID_USUARIO, NOME, DATA_ADMISSAO, SALARIO, DATA_NASCIMENTO, CARGO)
    VALUES(v_id + 1, ID_USUARIO_IN, NOME_IN, DATA_ADMISSAO_IN, SALARIO_IN, DATA_NASCIMENTO_IN, CARGO_IN);
END;
/

CREATE OR REPLACE PROCEDURE REMOVER_FUNCIONARIO(CODIGO IN NUMBER) IS
BEGIN
    DELETE FROM FUNCIONARIO WHERE ID_FUNCIONARIO = CODIGO;
END;
/

CREATE OR REPLACE FUNCTION BUSCAR_FUNCIONARIO(CODIGO IN NUMBER) RETURN VARCHAR2 IS
    v_nome VARCHAR2(255);
BEGIN
    SELECT NOME INTO v_nome FROM FUNCIONARIO WHERE ID_FUNCIONARIO = CODIGO;
    RETURN 'Funcionario: ' || v_nome;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Funcionário com o código ' || CODIGO || ' não encontrado.';
END;
/

CREATE OR REPLACE PROCEDURE ATUALIZAR_SALARIO(CODIGO IN NUMBER, NOVO_SALARIO IN NUMBER) IS
BEGIN
    UPDATE FUNCIONARIO SET SALARIO = NOVO_SALARIO WHERE ID_FUNCIONARIO = CODIGO;
END;
/


/***************/
/* CRUD - MESA */
/***************/

CREATE OR REPLACE PROCEDURE CADASTRAR_MESA(DISPONIVEL_IN IN NUMBER) IS
    v_id NUMBER;
BEGIN
    SELECT NVL(MAX(ID_MESA), 0) INTO v_id FROM MESA;
    INSERT INTO MESA(ID_MESA, DISPONIVEL) VALUES(v_id + 1, DISPONIVEL_IN);
END;
/

CREATE OR REPLACE PROCEDURE REMOVER_MESA(CODIGO IN NUMBER) IS
BEGIN
    DELETE FROM MESA WHERE ID_MESA = CODIGO;
END;
/

CREATE OR REPLACE FUNCTION BUSCAR_MESA(CODIGO IN NUMBER) RETURN VARCHAR2 IS
    v_disp NUMBER;
BEGIN
    SELECT DISPONIVEL INTO v_disp FROM MESA WHERE ID_MESA = CODIGO;
    RETURN 'Mesa ' || CODIGO || ' Disponivel: ' || v_disp;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Mesa ' || CODIGO || ' não encontrada.';
END;
/

CREATE OR REPLACE PROCEDURE ATUALIZAR_MESA(CODIGO IN NUMBER, STATUS_IN IN NUMBER) IS
BEGIN
    UPDATE MESA SET DISPONIVEL = STATUS_IN WHERE ID_MESA = CODIGO;
END;
/


/*****************/
/* CRUD - PEDIDO */
/*****************/

CREATE OR REPLACE PROCEDURE CADASTRAR_PEDIDO(ID_COMANDA_IN IN NUMBER, DATA_HORA_IN IN DATE, STATUS_IN IN VARCHAR2) IS
    v_id NUMBER;
BEGIN
    SELECT NVL(MAX(ID_PEDIDO), 0) INTO v_id FROM PEDIDO;
    INSERT INTO PEDIDO(ID_PEDIDO, ID_COMANDA, DATA_HORA, STATUS)
    VALUES(v_id + 1, ID_COMANDA_IN, DATA_HORA_IN, STATUS_IN);
END;
/

CREATE OR REPLACE PROCEDURE REMOVER_PEDIDO(CODIGO IN NUMBER) IS
BEGIN
    DELETE FROM PEDIDO WHERE ID_PEDIDO = CODIGO;
END;
/

CREATE OR REPLACE FUNCTION BUSCAR_PEDIDO(CODIGO IN NUMBER) RETURN VARCHAR2 IS
    v_status VARCHAR2(255);
BEGIN
    SELECT STATUS INTO v_status FROM PEDIDO WHERE ID_PEDIDO = CODIGO;
    RETURN 'Pedido ' || CODIGO || ' - ' || v_status;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Pedido ' || CODIGO || ' não encontrado.';
END;
/

CREATE OR REPLACE PROCEDURE ATUALIZAR_STATUS_PEDIDO(CODIGO IN NUMBER, NOVO_STATUS IN VARCHAR2) IS
BEGIN
    UPDATE PEDIDO SET STATUS = NOVO_STATUS WHERE ID_PEDIDO = CODIGO;
END;
/


/******************/
/* CRUD - PRODUTO */
/******************/

CREATE OR REPLACE PROCEDURE ADICIONAR_PRODUTO_ESTOQUE(ID_PRODUTO_IN IN INTEGER, QUANTIDADE_IN IN INTEGER) AS
    V_QTD_ATUAL NUMBER := 0;
BEGIN
    SELECT QUANTIDADE INTO V_QTD_ATUAL FROM PRODUTO WHERE ID_PRODUTO = ID_PRODUTO_IN;
    
    V_QTD_ATUAL := V_QTD_ATUAL + QUANTIDADE_IN;
    
    UPDATE PRODUTO SET QUANTIDADE = V_QTD_ATUAL WHERE ID_PRODUTO = ID_PRODUTO_IN;
    DBMS_OUTPUT.PUT_LINE('Nova quantidade em estoque: ' || V_QTD_ATUAL);
END;
/

CREATE OR REPLACE PROCEDURE REMOVER_PRODUTO_ESTOQUE(ID_PRODUTO_IN IN INTEGER, QUANTIDADE_IN IN INTEGER) AS
    V_QTD_ATUAL NUMBER := 0;
BEGIN
    SELECT QUANTIDADE INTO V_QTD_ATUAL FROM PRODUTO WHERE ID_PRODUTO = ID_PRODUTO_IN;
    
    IF (V_QTD_ATUAL - QUANTIDADE_IN < 0) THEN
        RAISE_APPLICATION_ERROR(-20020, 'ESTOQUE INSUFICIENTE PARA REMOÇÃO. Atual: ' || V_QTD_ATUAL);
    END IF;

    V_QTD_ATUAL := V_QTD_ATUAL - QUANTIDADE_IN;
    
    UPDATE PRODUTO SET QUANTIDADE = V_QTD_ATUAL WHERE ID_PRODUTO = ID_PRODUTO_IN;
    DBMS_OUTPUT.PUT_LINE('Nova quantidade em estoque: ' || V_QTD_ATUAL);
END;
/

CREATE OR REPLACE PROCEDURE CADASTRAR_PRODUTO(
    NOME_IN IN VARCHAR2, 
    PRECO_IN IN NUMBER, 
    OBS_IN IN VARCHAR2, 
    ID_AREA_IN IN NUMBER, 
    DISPONIVEL_IN IN NUMBER,
    QUANTIDADE_IN IN NUMBER DEFAULT 0
) IS
    v_id NUMBER;
BEGIN
    SELECT NVL(MAX(ID_PRODUTO), 0) INTO v_id FROM PRODUTO;

    INSERT INTO PRODUTO(ID_PRODUTO, NOME_PRODUTO, PRECO_PRODUTO, OBSERVACAO_PRODUTO, ID_AREA, DISPONIVEL, QUANTIDADE)
    VALUES(v_id + 1, NOME_IN, PRECO_IN, OBS_IN, ID_AREA_IN, DISPONIVEL_IN, QUANTIDADE_IN);
END;
/

CREATE OR REPLACE PROCEDURE REMOVER_PRODUTO(CODIGO IN NUMBER) IS
BEGIN
    DELETE FROM PRODUTO WHERE ID_PRODUTO = CODIGO;
END;
/

CREATE OR REPLACE FUNCTION BUSCAR_PRODUTO(CODIGO IN NUMBER) RETURN VARCHAR2 IS
    v_nome VARCHAR2(255);
BEGIN
    SELECT NOME_PRODUTO INTO v_nome FROM PRODUTO WHERE ID_PRODUTO = CODIGO;
    RETURN 'Produto: ' || v_nome;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Produto com o código ' || CODIGO || ' não encontrado.';
END;
/

CREATE OR REPLACE PROCEDURE ATUALIZAR_PRECO_PRODUTO(CODIGO IN NUMBER, NOVO_PRECO IN NUMBER) IS
BEGIN
    UPDATE PRODUTO SET PRECO_PRODUTO = NOVO_PRECO WHERE ID_PRODUTO = CODIGO;
END;
/

CREATE OR REPLACE PROCEDURE ATUALIZAR_OBS_PRODUTO(CODIGO IN NUMBER, NOVA_OBS IN VARCHAR2) IS
BEGIN
    UPDATE PRODUTO SET OBSERVACAO_PRODUTO = NOVA_OBS WHERE ID_PRODUTO = CODIGO;
END;
/