/* CRUD - ÁREA */
/***************/
SELECT * FROM AREA ORDER BY ID_AREA;

CREATE OR REPLACE PROCEDURE CADASTRAR_AREA(NOME IN VARCHAR2) IS
    v_num_areas NUMBER := -99;
BEGIN
    SELECT NVL(MAX(ID_AREA),0) INTO v_num_areas FROM AREA;
        
    INSERT INTO AREA(NOME_AREA, ID_AREA) VALUES(NOME, v_num_areas+1);
END;
/
 // TRIGGER (SE JA HOUVER UMA AREA COM ESSE NOME, RETORNAR ERRO)

EXEC CADASTRAR_AREA('COZINHA 7');

CREATE OR REPLACE PROCEDURE REMOVER_AREA_CODIGO(CODIGO IN NUMBER) IS
BEGIN
    DELETE FROM AREA A WHERE A.ID_AREA = CODIGO;
END;
/
CREATE OR REPLACE PROCEDURE REMOVER_AREA_NOME(NOME IN VARCHAR2) IS
BEGIN
    DELETE FROM AREA A WHERE A.NOME_AREA = NOME;
END;
/
// TRIGGER SE NÃO ACHAR A AREA

EXEC REMOVER_AREA_CODIGO(4);

EXEC REMOVER_AREA_NOME('COZINHA 7');

CREATE OR REPLACE FUNCTION BUSCAR_AREA_CODIGO(CODIGO IN NUMBER) RETURN VARCHAR2 IS
    v_codigo_area VARCHAR2(255);
    v_nome_area VARCHAR2(255);
    v_ret VARCHAR2(255);
BEGIN
    SELECT A.ID_AREA, A.NOME_AREA
    INTO v_codigo_area, v_nome_area
    FROM AREA A
    WHERE CODIGO = A.ID_AREA;
    
    v_ret := 'Codigo(' || v_codigo_area || ') - Área: ' || v_nome_area;
    RETURN v_ret;
END;
/

DECLARE
    v_num_areas NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_num_areas FROM AREA;
    FOR x in 1..v_num_areas LOOP
        DBMS_OUTPUT.PUT_LINE(BUSCAR_AREA_CODIGO(x));
    END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE ATUALIZAR_NOME_AREA(CODIGO IN NUMBER, NOVO_NOME IN VARCHAR2) IS
BEGIN
    UPDATE AREA A SET A.NOME_AREA = NOVO_NOME
    WHERE CODIGO = A.ID_AREA;
END;
/

EXEC ATUALIZAR_NOME_AREA(1, 'COZINHA 1');

/******************/
/* CRUD - CLUENTE */
/******************/
SELECT * FROM CLIENTE;
CREATE OR REPLACE PROCEDURE CADASTRAR_CLIENTE(NOME IN VARCHAR2) IS 
    v_id NUMBER;
BEGIN
    SELECT NVL(MAX(ID_CLIENTE),0)
    INTO v_id
    FROM CLIENTE;

    INSERT INTO CLIENTE(ID_CLIENTE, NOME_CLIENTE)
    VALUES(v_id + 1, NOME);
END;
/

CREATE OR REPLACE PROCEDURE REMOVER_CLIENTE_CODIGO(CODIGO IN NUMBER) IS
BEGIN
    DELETE FROM CLIENTE
    WHERE ID_CLIENTE = CODIGO;
END;
/

CREATE OR REPLACE FUNCTION BUSCAR_CLIENTE_CODIGO(CODIGO IN NUMBER) RETURN VARCHAR2 IS
    v_nome VARCHAR2(255);
BEGIN
    SELECT NOME_CLIENTE
    INTO v_nome
    FROM CLIENTE
    WHERE ID_CLIENTE = CODIGO;

    RETURN 'Codigo(' || CODIGO || ') - Cliente: ' || v_nome;
END;
/

CREATE OR REPLACE PROCEDURE ATUALIZAR_CLIENTE(CODIGO IN NUMBER, NOVO_NOME IN VARCHAR2) IS
BEGIN
    UPDATE CLIENTE
    SET NOME_CLIENTE = NOVO_NOME
    WHERE ID_CLIENTE = CODIGO;
END;
/

/******************/
/* CRUD - COMANDA */
/******************/
SELECT * FROM COMANDA;
CREATE OR REPLACE PROCEDURE CADASTRAR_COMANDA(ID_MESA_IN IN NUMBER, NOME_CLIENTE_IN IN VARCHAR2, PRECO_TOTAL_IN IN NUMBER) IS
    v_id NUMBER;
BEGIN
    SELECT NVL(MAX(ID_COMANDA),0)
    INTO v_id
    FROM COMANDA;

    INSERT INTO COMANDA
    VALUES(
        v_id + 1,
        ID_MESA_IN,
        NOME_CLIENTE_IN,
        PRECO_TOTAL_IN
    );
END;
/

CREATE OR REPLACE PROCEDURE REMOVER_COMANDA(CODIGO IN NUMBER) IS
BEGIN
    DELETE FROM COMANDA
    WHERE ID_COMANDA = CODIGO;
END;
/

CREATE OR REPLACE FUNCTION BUSCAR_COMANDA(CODIGO IN NUMBER) RETURN VARCHAR2 IS
    v_cliente VARCHAR2(255);
BEGIN
    SELECT NOME_CLIENTE
    INTO v_cliente
    FROM COMANDA
    WHERE ID_COMANDA = CODIGO;

    RETURN 'Comanda ' || CODIGO || ' - Cliente: ' || v_cliente;
END;
/

CREATE OR REPLACE PROCEDURE ATUALIZAR_COMANDA(
    CODIGO IN NUMBER,
    NOVO_TOTAL IN NUMBER
) IS
BEGIN
    UPDATE COMANDA
    SET PRECO_TOTAL = NOVO_TOTAL
    WHERE ID_COMANDA = CODIGO;
END;
/

/**********************/
/* CRUD - FUNCIONARIO */
/**********************/
SELECT * FROM FUNCIONARIOS;
CREATE OR REPLACE PROCEDURE CADASTRAR_FUNCIONARIO(ID_USUARIO_IN IN NUMBER, NOME_IN IN VARCHAR2, DATA_ADMISSAO_IN IN DATE, SALARIO_IN IN NUMBER, DATA_NASCIMENTO_IN IN DATE) IS
    v_id NUMBER;
BEGIN
    SELECT NVL(MAX(ID_FUNCIONARIO),0)
    INTO v_id
    FROM FUNCIONARIOS;

    INSERT INTO FUNCIONARIOS
    VALUES(
        v_id + 1,
        ID_USUARIO_IN,
        NOME_IN,
        DATA_ADMISSAO_IN,
        SALARIO_IN,
        DATA_NASCIMENTO_IN
    );
END;
/

CREATE OR REPLACE PROCEDURE REMOVER_FUNCIONARIO(CODIGO IN NUMBER) IS
BEGIN
    DELETE FROM FUNCIONARIOS
    WHERE ID_FUNCIONARIO = CODIGO;
END;
/

CREATE OR REPLACE FUNCTION BUSCAR_FUNCIONARIO(CODIGO IN NUMBER) RETURN VARCHAR2 IS
    v_nome VARCHAR2(255);
BEGIN
    SELECT NOME
    INTO v_nome
    FROM FUNCIONARIOS
    WHERE ID_FUNCIONARIO = CODIGO;

    RETURN 'Funcionario: ' || v_nome;
END;
/

CREATE OR REPLACE PROCEDURE ATUALIZAR_SALARIO(CODIGO IN NUMBER, NOVO_SALARIO IN NUMBER) IS
BEGIN
    UPDATE FUNCIONARIOS
    SET SALARIO = NOVO_SALARIO
    WHERE ID_FUNCIONARIO = CODIGO;
END;
/

/***************/
/* CRUD - MESA */
/***************/
SELECT * FROM MESA;

CREATE OR REPLACE PROCEDURE CADASTRAR_MESA(DISPONIVEL_IN IN NUMBER) IS
    v_id NUMBER;
BEGIN
    SELECT NVL(MAX(ID_MESA),0)
    INTO v_id
    FROM MESA;

    INSERT INTO MESA
    VALUES(v_id + 1, DISPONIVEL_IN);
END;
/

CREATE OR REPLACE PROCEDURE REMOVER_MESA(CODIGO IN NUMBER) IS
BEGIN
    DELETE FROM MESA
    WHERE ID_MESA = CODIGO;
END;
/

CREATE OR REPLACE FUNCTION BUSCAR_MESA(CODIGO IN NUMBER) RETURN VARCHAR2 IS
    v_disp NUMBER;
BEGIN
    SELECT DISPONIVEL
    INTO v_disp
    FROM MESA
    WHERE ID_MESA = CODIGO;

    RETURN 'Mesa ' || CODIGO || ' Disponivel: ' || v_disp;
END;
/

CREATE OR REPLACE PROCEDURE ATUALIZAR_MESA(CODIGO IN NUMBER, STATUS_IN IN NUMBER) IS
BEGIN
    UPDATE MESA
    SET DISPONIVEL = STATUS_IN
    WHERE ID_MESA = CODIGO;
END;
/

/*****************/
/* CRUD - PEDIDO */
/*****************/
SELECT * FROM PEDIDO;

CREATE OR REPLACE PROCEDURE CADASTRAR_PEDIDO(ID_COMANDA_IN IN NUMBER, DATA_HORA_IN IN DATE, STATUS_IN IN VARCHAR2) IS
    v_id NUMBER;
BEGIN
    SELECT NVL(MAX(ID_PEDIDO),0)
    INTO v_id
    FROM PEDIDO;

    INSERT INTO PEDIDO
    VALUES(
        v_id + 1,
        ID_COMANDA_IN,
        DATA_HORA_IN,
        STATUS_IN
    );
END;
/

CREATE OR REPLACE PROCEDURE REMOVER_PEDIDO(CODIGO IN NUMBER) IS
BEGIN
    DELETE FROM PEDIDO
    WHERE ID_PEDIDO = CODIGO;
END;
/

CREATE OR REPLACE FUNCTION BUSCAR_PEDIDO(CODIGO IN NUMBER) RETURN VARCHAR2 IS
    v_status VARCHAR2(255);
BEGIN
    SELECT STATUS
    INTO v_status
    FROM PEDIDO
    WHERE ID_PEDIDO = CODIGO;

    RETURN 'Pedido ' || CODIGO || ' - ' || v_status;
END;
/

CREATE OR REPLACE PROCEDURE ATUALIZAR_STATUS_PEDIDO(CODIGO IN NUMBER, NOVO_STATUS IN VARCHAR2) IS
BEGIN
    UPDATE PEDIDO
    SET STATUS = NOVO_STATUS
    WHERE ID_PEDIDO = CODIGO;
END;
/

/******************/
/* CRUD - PRODUTO */
/******************/
SELECT * FROM PRODUTO;

CREATE OR REPLACE PROCEDURE CADASTRAR_PRODUTO(NOME_IN IN VARCHAR2, PRECO_IN IN NUMBER, OBS_IN IN VARCHAR2, ID_AREA_IN IN NUMBER, DISPONIVEL_IN IN NUMBER) IS
    v_id NUMBER;
BEGIN
    SELECT NVL(MAX(ID_PRODUTO),0)
    INTO v_id
    FROM PRODUTO;

    INSERT INTO PRODUTO
    VALUES(
        v_id + 1,
        NOME_IN,
        PRECO_IN,
        OBS_IN,
        ID_AREA_IN,
        DISPONIVEL_IN
    );
END;
/

CREATE OR REPLACE PROCEDURE REMOVER_PRODUTO(CODIGO IN NUMBER) IS
BEGIN
    DELETE FROM PRODUTO
    WHERE ID_PRODUTO = CODIGO;
END;
/

CREATE OR REPLACE FUNCTION BUSCAR_PRODUTO(CODIGO IN NUMBER) RETURN VARCHAR2 IS
    v_nome VARCHAR2(255);
BEGIN
    SELECT NOME_PRODUTO
    INTO v_nome
    FROM PRODUTO
    WHERE ID_PRODUTO = CODIGO;

    RETURN 'Produto: ' || v_nome;
END;
/

CREATE OR REPLACE PROCEDURE ATUALIZAR_PRECO_PRODUTO(CODIGO IN NUMBER, NOVO_PRECO IN NUMBER) IS
BEGIN
    UPDATE PRODUTO
    SET PRECO_PRODUTO = NOVO_PRECO
    WHERE ID_PRODUTO = CODIGO;
END;
/

CREATE OR REPLACE PROCEDURE ATUALIZAR_OBS_PRODUTO(CODIGO IN NUMBER, NOVA_OBS IN NUMBER) IS
BEGIN
    UPDATE PRODUTO
    SET OBSERVACAO_PRODUTO = NOVA_OBS
    WHERE ID_PRODUTO = CODIGO;
END;
/