SET SERVEROUTPUT ON;

/*****************/
/* CRUD - ÁREA   */
/*****************/
CREATE OR REPLACE TRIGGER TRG_BIU_AREA
BEFORE INSERT OR UPDATE ON AREA
FOR EACH ROW
BEGIN
    IF :NEW.NOME_AREA IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'NÃO É PERMITIDO O CADASTRO DE NOMES VAZIOS (AREAS)');
    END IF;
END;
/

/******************/
/* CRUD - CLIENTE */
/******************/
CREATE OR REPLACE TRIGGER TRG_BIU_CLIENTE
BEFORE INSERT OR UPDATE ON CLIENTE
FOR EACH ROW
BEGIN
    IF :NEW.NOME_CLIENTE IS NULL THEN
        RAISE_APPLICATION_ERROR(-20002, 'NÃO É PERMITIDO O CADASTRO DE NOMES VAZIOS (CLIENTES)');
    END IF;
END;
/

/******************/
/* CRUD - COMANDA */
/******************/
CREATE OR REPLACE TRIGGER TRG_BIU_COMANDA
BEFORE INSERT OR UPDATE ON COMANDA
FOR EACH ROW
DECLARE
    v_status_mesa NUMBER;
BEGIN
    IF :NEW.ID_MESA IS NOT NULL THEN
        BEGIN
            SELECT DISPONIVEL INTO v_status_mesa 
            FROM MESA 
            WHERE ID_MESA = :NEW.ID_MESA;
            
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20003, 'NÃO FOI ENCONTRADA UMA MESA COM ESSE ID.');
        END;
    END IF;
END;
/

/**********************/
/* CRUD - FUNCIONARIO */
/**********************/
CREATE OR REPLACE TRIGGER TRG_BIU_FUNCIONARIO
BEFORE INSERT OR UPDATE ON FUNCIONARIO
FOR EACH ROW
BEGIN
    IF :NEW.NOME IS NULL THEN
        RAISE_APPLICATION_ERROR(-20004, 'NÃO É PERMITIDO O CADASTRO DE NOMES VAZIOS (FUNCIONARIO)');
    END IF;

    IF :NEW.CARGO IS NULL THEN
        RAISE_APPLICATION_ERROR(-20005, 'NÃO É PERMITIDO O CADASTRO DE CARGOS VAZIOS (FUNCIONARIO)');
    END IF;

    IF :NEW.SALARIO < 0 THEN
        RAISE_APPLICATION_ERROR(-20006, 'NÃO É PERMITIDO O CADASTRO DE VALORES MENORES QUE ZERO (FUNCIONARIO - SALARIO)');
    END IF;

    IF :NEW.DATA_ADMISSAO IS NULL THEN
        :NEW.DATA_ADMISSAO := SYSDATE;
    END IF;
END;
/

/*****************/
/* CRUD - PEDIDO */
/*****************/
CREATE OR REPLACE TRIGGER TRG_BIU_PEDIDO
BEFORE INSERT OR UPDATE ON PEDIDO
FOR EACH ROW
BEGIN
    IF :NEW.ID_COMANDA IS NULL THEN
        RAISE_APPLICATION_ERROR(-20011, 'O ID DA COMANDA NÃO PODE ESTAR VAZIO (PEDIDO)');
    END IF;
END;
/

/******************/
/* CRUD - PRODUTO */
/******************/
CREATE OR REPLACE TRIGGER TRG_BIU_PRODUTO
BEFORE INSERT OR UPDATE ON PRODUTO
FOR EACH ROW
DECLARE
    v_count_area INTEGER := 0;
BEGIN
    IF :NEW.NOME_PRODUTO IS NULL THEN
        RAISE_APPLICATION_ERROR(-20007, 'NÃO É PERMITIDO O CADASTRO DE NOMES VAZIOS (PRODUTO)');
    END IF;

    IF :NEW.PRECO_PRODUTO < 0 THEN
        RAISE_APPLICATION_ERROR(-20008, 'NÃO É PERMITIDO O CADASTRO DE VALORES MENORES QUE ZERO (PRODUTO - PRECO)');
    END IF;

    IF :NEW.QUANTIDADE < 0 THEN
        RAISE_APPLICATION_ERROR(-20009, 'NÃO É PERMITIDO O CADASTRO DE VALORES MENORES QUE ZERO (PRODUTO - QUANTIDADE)');
    END IF;

    IF :NEW.OBSERVACAO_PRODUTO IS NULL THEN
        RAISE_APPLICATION_ERROR(-20013, 'A OBSERVAÇÃO DO PRODUTO NÃO PODE SER VAZIA');
    END IF;

    IF :NEW.ID_AREA IS NOT NULL THEN
        SELECT COUNT(*) INTO v_count_area FROM AREA WHERE ID_AREA = :NEW.ID_AREA;
        IF v_count_area = 0 THEN
            RAISE_APPLICATION_ERROR(-20010, 'NÃO FOI ENCONTRADA NENHUMA ÁREA COM ESSE ID (' || :NEW.ID_AREA || ')');
        END IF;
    END IF;
END;
/

/**************************/
/* CRUD - PRODUTO_PEDIDO  */
/**************************/
CREATE OR REPLACE TRIGGER TRG_BIU_PRODUTO_PEDIDO
BEFORE INSERT OR UPDATE ON PRODUTO_PEDIDO
FOR EACH ROW
BEGIN
    IF :NEW.PRECO_UNI < 0 THEN
        RAISE_APPLICATION_ERROR(-20014, 'O PREÇO UNITÁRIO NÃO PODE SER MENOR QUE ZERO (PRODUTO_PEDIDO)');
    END IF;

    IF :NEW.QUANTIDADE < 0 THEN
        RAISE_APPLICATION_ERROR(-20015, 'A QUANTIDADE NÃO PODE SER MENOR QUE ZERO (PRODUTO_PEDIDO)');
    END IF;
END;
/

/******************/
/* CRUD - USUARIO */
/******************/
CREATE OR REPLACE TRIGGER TRG_BIU_USUARIO
BEFORE INSERT OR UPDATE ON USUARIO
FOR EACH ROW
BEGIN
    IF :NEW.NOME IS NULL THEN
        RAISE_APPLICATION_ERROR(-20016, 'NÃO É PERMITIDO O CADASTRO DE NOMES VAZIOS (USUARIO)');
    END IF;

    IF :NEW.CARGO IS NULL THEN
        RAISE_APPLICATION_ERROR(-20017, 'NÃO É PERMITIDO O CADASTRO DE CARGOS VAZIOS (USUARIO)');
    END IF;
END;
/